name: Build Xtensa Assembly

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Python e Esptool
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install esptool

      - name: Instalar Toolchain Xtensa (ESP32)
        uses: espressif/git-action-esp-idf@v1
        with:
          esp-idf-version: 'v5.1'

      - name: Executar o Make
        run: |
          make
