name: Build Xtensa Assembly

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Python e Esptool
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install esptool

      - name: Compilar, Linkar e Converter com Toolchain do ESP32
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.1'
          command: |
            xtensa-esp32-elf-gcc -c start.S -o start.o
            xtensa-esp32-elf-ld write.o -o start.elf
            esptool.py --chip esp32 elf2image start.elf -o kernel.bin
