name: Kernel Xtensa CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.1

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Compilar, Linkar e Converter
        run: |
          . $IDF_PATH/export.sh
          xtensa-esp32-elf-gcc -c start.S -o start.o
          xtensa-esp32-elf-ld start.o -o start.elf
          esptool.py --chip esp32 elf2image start.elf -o start.bin
